---
- name: Install MongoDB.
  hosts: db_servers
  gather_facts: true
  become: true
  vars:
    mongodb_version: "{{ version | default('8.2') }}"
    mongodb_repo_name: "mongodb-enterprise-{{ mongodb_version }}"
    mongodb_pkg_name: "mongodb-enterprise{{ '-server' if ansible_distribution_major_version | int >= 9 else '' }}"
    mongosh_version: 2.5.10
  tasks:

    - name: Remove potentially outdated MongoDB repo files.
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: >-
        {{ query('ansible.builtin.fileglob', '/etc/yum.repos.d/mongodb*')
           | reject('search', mongodb_repo_name ~ '.repo')
           | list }}

    - name: "Create repo file for {{ mongodb_repo_name }}"
      ansible.builtin.template:
        src: mongodb-enterprise.repo.j2
        dest: "/etc/yum.repos.d/{{ mongodb_repo_name }}.repo"
        owner: root
        group: root
        mode: '0644'

    - name: "Install mongodb-entprise {{ mongodb_version }}"
      ansible.builtin.dnf:
        name: "{{ mongodb_pkg_name }}"
        state: present

    - name: Download mongodb shell.
      ansible.builtin.get_url:
        url: "https://downloads.mongodb.com/compass/mongosh-{{ mongosh_version }}-linux-{{ ansible_architecture }}.tgz"
        dest: "/tmp/mongosh-{{ mongosh_version }}-linux-{{ ansible_architecture }}.tgz"
        mode: "0644"

    - name: Extract mongosh into /opt
      ansible.builtin.unarchive:
        src: "/tmp/mongosh-{{ mongosh_version }}-linux-{{ ansible_architecture }}.tgz"
        dest: "/opt/"
        remote_src: true
        creates: "/opt/mongosh-{{ mongosh_version }}-linux-{{ ansible_architecture }}/bin/mongosh"

    - name: Symlink mongosh into /usr/local/bin
      ansible.builtin.file:
        src: "/opt/mongosh-{{ mongosh_version }}-linux-{{ ansible_architecture }}/bin/mongosh"
        dest: "/usr/local/bin/mongosh"
        state: link

    - name: Start mongod service.
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true

    - name: Check mongod status
      ansible.builtin.systemd:
        name: mongod
      register: mongod_check
      changed_when: false
      failed_when: mongod_check.status.ActiveState != 'active'

    - name: Print mongod status for verification.
      ansible.builtin.debug:
        msg: "{{ mongod_check.status.ActiveState }}"

    - name: Check mongod version.
      ansible.builtin.command: mongod --version
      register: mongod_version
      changed_when: false
      failed_when: mongodb_version not in mongod_version.stdout

    - name: Print mongod version for verification.
      ansible.builtin.debug:
        msg: "{{ mongod_version.stdout_lines[0] }}"

    - name: Verify MongoDB Enterprise Edition is ready and waiting for connections.
      ansible.builtin.wait_for:
        path: /var/log/mongodb/mongod.log
        search_regex: 'Waiting for connections'
        timeout: 30

    - name: Congratulations!
      ansible.builtin.debug:
        msg: "MongoDB installation complete. {{ mongod_version.stdout_lines[0] }} is {{ mongod_check.status.ActiveState }}."
