---
- name: Uninstall MongoDB on localhost.
  hosts: db_servers
  gather_facts: true
  become: true
  tasks:
    - name: Gather info about installed services.
      tags: debug
      ansible.builtin.service_facts:

    - name: Stop mongod service.
      tags: debug
      ansible.builtin.service:
        name: mongod
        state: stopped
      when: ansible_facts.services is search("mongod.service")

    - name: Uninstall MongoDB.
      ansible.builtin.dnf:
        name: mongodb-enterprise
        state: absent
        autoremove: true

    - name: Remove data and log directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/log/mongodb
        - /var/lib/mongo

    - name: Uninstall complete.
      ansible.builtin.debug:
        msg: "MongoDB has been uninstalled successfully."
